name: CI
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Bump patch version number
      run: |
        # Check if the build was triggered by an individual commit
        if [ "$GITHUB_EVENT_NAME" = "push" ]; then
          # Set patch version and push commit
          git config --global user.email "you@example.com"
          git config --global user.name "GitHub Actions"
          
          # Extract the current version number
          version=$(sed -n "s/version='\(.*\)'/\1/p" VERSION)            

          pip install bump2version && \
          bump2version --no-commit --current-version $version patch VERSION    

          # Extract the new version number
          version=$(sed -n "s/version='\(.*\)'/\1/p" VERSION)                                  
          git commit -am "Version upgraded to $version [skip ci]"
        else
          version="$GITHUB_REF-$(sed -n "s/version='\(.*\)'/\1/p" VERSION)"
        fi
        
    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: ${{ env.version }}